# Generated by Django 5.1.7 on 2025-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbearia",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="barbearias/"),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
