# Generated by Django 5.1.7 on 2025-04-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_barbearia_cpf_barbearia_descricao_barbearia_imagem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbearia",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="barbearia",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
