# Generated by Django 5.1.7 on 2025-04-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_barbearia_plano"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="barbearia",
            managers=[],
        ),
        migrations.AlterField(
            model_name="barbearia",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
