# Generated by Django 5.1.7 on 2025-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_barbearia_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbearia",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
