# Generated by Django 5.1.7 on 2025-04-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_barbearia_managers_alter_barbearia_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbearia",
            name="url_personalizada",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="uuid",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
