# Generated by Django 5.1.7 on 2025-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_barbearia_cnpj_alter_barbearia_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbearia",
            name="telefone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
