# Generated by Django 5.1.7 on 2025-04-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_barbearia_url_personalizada_barbearia_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barbearia",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="barbearia",
            name="url_personalizada",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
