# Generated by Django 5.1.7 on 2025-04-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_barbearia_telefone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="cancelado",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMADO", "Confirmado"),
                    ("CANCELADO", "Cancelado"),
                    ("EXPIRADO", "Expirado"),
                    ("CONCLUIDO", "Concluído"),
                ],
                default="CONFIRMADO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.funcionario"
            ),
        ),
    ]
