# Generated by Django 5.1.7 on 2025-04-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_barbearia_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barbearia",
            name="url_personalizada",
        ),
    ]
