# Generated by Django 5.1.7 on 2025-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_agendamento_cancelado_agendamento_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="clientes/"),
        ),
    ]
