# Generated by Django 5.1.7 on 2025-04-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_barbearia_url_personalizada"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioFuncionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (5, "Sexta-feira"),
                            (6, "Sábado"),
                        ]
                    ),
                ),
                ("horario_abertura", models.TimeField(blank=True, null=True)),
                ("horario_fechamento", models.TimeField(blank=True, null=True)),
                ("fechado", models.BooleanField(default=False)),
                (
                    "barbearia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana"],
                "unique_together": {("barbearia", "dia_semana")},
            },
        ),
    ]
