# Generated by Django 5.1.7 on 2025-04-08 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_cliente_email_alter_barbearia_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamento",
            old_name="hora",
            new_name="hora_inicio",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="barbearia",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="status",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="users.clienteuser",
            ),
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "barbearia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agendamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="users.funcionario",
            ),
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("duracao_minutos", models.PositiveIntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "barbearia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.servico",
            ),
        ),
    ]
