# Generated by Django 5.1.7 on 2025-04-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_barbeariapasswordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="preco_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
