# Generated by Django 5.1.7 on 2025-04-11 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_cliente_barbearia_alter_funcionario_barbearia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnderecoBarbearia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("estado", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "barbearia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endereco",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
