# Generated by Django 5.1.7 on 2025-04-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_barbeariauser_date_joined_clienteuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="custo",
            name="tipo",
            field=models.CharField(
                choices=[("fixed", "Fixo"), ("variable", "Variável")],
                default="fixed",
                max_length=10,
            ),
        ),
    ]
