# Generated by Django 5.1.7 on 2025-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_custo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienteuser",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
