# Generated by Django 5.1.7 on 2025-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_clienteuser_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbearia",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
