# Generated by Django 5.1.7 on 2025-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_barbearia_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="metodo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pix", "Pix"),
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                    ("dinheiro", "Dinheiro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="cash",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="credit_card",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="debit_card",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="pix",
            field=models.BooleanField(default=True),
        ),
    ]
