# Generated by Django 5.1.7 on 2025-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_agendamento_metodo_pagamento_barbearia_cash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="metodo_pagamento",
            field=models.CharField(
                choices=[
                    ("pix", "Pix"),
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                    ("dinheiro", "Dinheiro"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
