# Generated by Django 5.1.7 on 2025-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_agendamento_metodo_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbearia",
            name="agendamento_sem_login",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="intervalo_agendamento",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="barbearia",
            name="prazo_cancelamento",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
