# Generated by Django 5.1.7 on 2025-05-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_barbearia_agendamento_sem_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barbearia",
            name="agendamento_sem_login",
        ),
    ]
