# Generated by Django 5.1.7 on 2025-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_barbearia_agendamento_sem_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="status",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="ativo",
                help_text="Indica se o cliente está ativo ou inativo na barbearia.",
                max_length=10,
            ),
        ),
    ]
