# Generated by Django 5.1.7 on 2025-05-25 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('plan_name', models.CharField(choices=[('Básico', 'Básico'), ('Profissional', 'Profissional'), ('Premium', 'Premium')], max_length=50)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbearia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
