# Generated by Django 5.1.7 on 2025-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_status_alter_subscription_barbearia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('canceled', 'Cancelada'), ('trial', 'Trial'), ('expired', 'Expirada')], default='pending', max_length=20),
        ),
    ]
