from .barbearia_serializer import BarbeariaSerializer
from .cliente_serializer import ClienteSerializer
from .agendamento_serializer import AgendamentoSerializer
from .horario_funcionamento_serializer import HorarioFuncionamento
from .cliente_user_serializer import ClienteLoginSerializer