from .barbearia.barbearia_serializer import BarbeariaSerializer
from .cliente.cliente_serializer import ClienteSerializer
from .agendamento_serializer import AgendamentoSerializer
from .barbearia.horario_funcionamento_serializer import HorarioFuncionamento
from .cliente.cliente_user_serializer import ClienteLoginSerializer